// Lista única de misiones de FachApp (todas con temática española).
// La usan scripts/missions.mjs (genera los seeds) y los tests.
export const pic = (seed) => `https://picsum.photos/seed/fachapp-${seed}/800/450`
const hashtag = (tag, days = 7) => ({
  type: 'post_with_hashtag',
  hashtag: tag,
  min_count: 1,
  window_days: days,
})

// n = número fijo del id en el seed local (10000000-0000-4000-a000-0000000000NN)
export const MISSIONS = [
  // --- Reto de la semana -----------------------------------------------------
  {
    n: 25,
    title: 'Foto con la bandera de España',
    featured: true,
    category: 'españa',
    difficulty: 'facil',
    points: 80,
    type: 'photo',
    description:
      'Hazte una foto con la rojigualda: en tu balcón, en un acto, en el pueblo o donde ondee con más arte. Puntos extra de orgullo si es grande (los puntos de verdad son los de la misión).',
    cover: 'bandera',
  },
  // --- España en X --------------------------------------------------------------
  {
    n: 23,
    title: '#España en X',
    category: 'redes',
    difficulty: 'facil',
    points: 50,
    type: 'x_auto',
    rules: hashtag('#España'),
    description:
      'Publica un post en X con el hashtag #España contando qué te gusta de tu tierra. Lo verificamos automáticamente.',
    cover: 'espana-x',
  },
  {
    n: 1,
    title: 'Estrena el #FachApp',
    category: 'redes',
    difficulty: 'facil',
    points: 50,
    type: 'x_auto',
    rules: hashtag('#FachApp'),
    description:
      'Publica un post en X con el hashtag #FachApp contando qué reto español vas a completar esta semana.',
    cover: 'hashtag',
  },
  {
    n: 30,
    title: '#12deOctubre en X',
    category: 'redes',
    difficulty: 'facil',
    points: 60,
    type: 'x_auto',
    rules: hashtag('#12deOctubre'),
    starts: '2026-10-05 00:00+02',
    ends: '2026-10-19 23:59+02',
    description: 'Felicita la Fiesta Nacional en X con el hashtag #12deOctubre.',
    cover: '12-octubre-x',
  },
  {
    n: 2,
    title: '100 patriotas',
    category: 'redes',
    difficulty: 'media',
    points: 150,
    type: 'x_auto',
    rules: { type: 'followers_min', value: 100 },
    description: 'Llega a 100 seguidores en tu cuenta de X.',
    cover: 'comunidad',
  },
  {
    n: 3,
    title: 'Embajador de España en X',
    category: 'redes',
    difficulty: 'media',
    points: 100,
    type: 'x_auto',
    rules: { type: 'post_count', min: 5, window_days: 7 },
    description: 'Publica al menos 5 posts en X en los últimos 7 días hablando de lo nuestro.',
    cover: 'activa',
  },
  // --- Política y actualidad --------------------------------------------------
  {
    n: 17,
    title: 'Selfie con alguien del PP',
    category: 'actualidad',
    difficulty: 'dificil',
    points: 200,
    type: 'photo',
    description:
      'Hazte un selfie con un cargo o personaje conocido del Partido Popular: en un mitin, un acto público o por la calle. Siempre pidiendo permiso y con buen rollo.',
    cover: 'selfie-pp',
  },
  {
    n: 13,
    title: 'Desfile del 12 de Octubre',
    category: 'españa',
    difficulty: 'media',
    points: 100,
    type: 'photo',
    starts: '2026-10-10 00:00+02',
    ends: '2026-10-13 23:59+02',
    description:
      'Fiesta Nacional: foto del desfile, de la Patrulla Águila pintando el cielo o de las banderas en los balcones de tu calle.',
    cover: 'desfile',
  },
  {
    n: 31,
    title: 'Día de la Constitución',
    category: 'españa',
    difficulty: 'facil',
    points: 60,
    type: 'photo',
    starts: '2026-12-01 00:00+01',
    ends: '2026-12-08 23:59+01',
    description:
      'El 6 de diciembre celebramos la Constitución de 1978. Foto con un ejemplar (o en un acto conmemorativo).',
    cover: 'constitucion',
  },
  {
    n: 26,
    title: 'Con la camiseta de La Roja',
    category: 'españa',
    difficulty: 'facil',
    points: 60,
    type: 'photo',
    description:
      'Foto con la camiseta de la Selección. Si es la de algún Mundial o Eurocopa ganados, ya eres leyenda.',
    cover: 'la-roja',
  },
  // --- Paisajes y patrimonio ----------------------------------------------------
  {
    n: 4,
    title: 'Atardecer en España',
    category: 'naturaleza',
    difficulty: 'facil',
    points: 80,
    type: 'photo',
    description: 'Haz una foto del atardecer desde tu rincón favorito de España.',
    cover: 'atardecer',
  },
  {
    n: 10,
    title: 'Amanecer en España',
    category: 'naturaleza',
    difficulty: 'dificil',
    points: 120,
    type: 'photo',
    description:
      'Madruga y fotografía un amanecer en cualquier punto de España. El café después te lo has ganado.',
    cover: 'amanecer',
  },
  {
    n: 7,
    title: 'Monumento de tu provincia',
    category: 'cultura',
    difficulty: 'media',
    points: 100,
    type: 'photo',
    description: 'Visita un monumento o lugar histórico de tu provincia y hazte una foto allí.',
    cover: 'monumento',
  },
  {
    n: 28,
    title: 'Patrimonio de la Humanidad',
    category: 'cultura',
    difficulty: 'media',
    points: 120,
    type: 'photo',
    description:
      'España es de los países con más lugares Patrimonio de la Humanidad: la Alhambra, la Mezquita de Córdoba, la Sagrada Familia, Santiago… Foto en uno de ellos.',
    cover: 'patrimonio',
  },
  {
    n: 6,
    title: 'Una etapa del Camino de Santiago',
    category: 'cultura',
    difficulty: 'dificil',
    points: 150,
    type: 'photo',
    description:
      'Haz una etapa del Camino (cualquiera vale) y sube una foto con la flecha amarilla o la concha. ¡Buen Camino!',
    cover: 'camino',
  },
  {
    n: 18,
    title: 'El toro de Osborne',
    category: 'españa',
    difficulty: 'media',
    points: 90,
    type: 'photo',
    description:
      'Busca uno de los toros de Osborne que vigilan nuestras carreteras y hazte una foto con él (sin ponerte en peligro en el arcén).',
    cover: 'toro-osborne',
  },
  {
    n: 9,
    title: 'Limpia una playa o un monte de España',
    category: 'naturaleza',
    difficulty: 'media',
    points: 150,
    type: 'photo',
    description:
      'Cuidar lo nuestro también es patriotismo: recoge basura en una playa, río o monte y sube una foto de lo que recogiste.',
    cover: 'limpieza',
  },
  // --- Gastronomía ---------------------------------------------------------------
  {
    n: 11,
    title: 'Tortilla: ¿con o sin cebolla?',
    category: 'gastronomía',
    difficulty: 'facil',
    points: 70,
    type: 'photo',
    description:
      'El debate que divide España. Sube tu tortilla de patatas y declara tu bando con #ConCebolla o #SinCebolla. Las de bote no cuentan.',
    cover: 'tortilla',
  },
  {
    n: 19,
    title: 'Paella como Dios manda',
    category: 'gastronomía',
    difficulty: 'media',
    points: 90,
    type: 'photo',
    description:
      'Paella valenciana de verdad: sin chorizo y con socarrat. Si lleva chorizo, la comunidad votará en consecuencia.',
    cover: 'paella',
  },
  {
    n: 27,
    title: 'Jamón, jamón',
    category: 'gastronomía',
    difficulty: 'facil',
    points: 60,
    type: 'photo',
    description: 'Foto de un buen plato de jamón ibérico (si lo cortas tú a cuchillo, mejor).',
    cover: 'jamon',
  },
  {
    n: 12,
    title: 'Las croquetas de la abuela',
    category: 'gastronomía',
    difficulty: 'facil',
    points: 60,
    type: 'photo',
    description:
      'Foto de las mejores croquetas que conozcas. Si son de tu abuela, puntos extra de ternura.',
    cover: 'croquetas',
  },
  {
    n: 5,
    title: 'Tapeo con amigos',
    category: 'gastronomía',
    difficulty: 'facil',
    points: 60,
    type: 'photo',
    description:
      'Sal de tapas con tus amigos y sube una foto de la mesa (sin caras si no quieren salir).',
    cover: 'tapas',
  },
  {
    n: 20,
    title: 'Oro líquido',
    category: 'gastronomía',
    difficulty: 'media',
    points: 70,
    type: 'photo',
    description:
      'España es la primera productora de aceite de oliva del mundo. Foto de tu AOVE español favorito o de una almazara.',
    cover: 'aceite',
  },
  // --- Tradiciones ----------------------------------------------------------------
  {
    n: 29,
    title: 'Fiestas de tu pueblo',
    category: 'tradiciones',
    difficulty: 'facil',
    points: 70,
    type: 'photo',
    description:
      'Verbena, procesión, peñas o charanga: foto de las fiestas patronales de tu pueblo o barrio.',
    cover: 'fiestas',
  },
  {
    n: 14,
    title: 'Castañas asadas',
    category: 'tradiciones',
    difficulty: 'facil',
    points: 50,
    type: 'photo',
    ends: '2026-12-15 23:59+01',
    description:
      'Llega el otoño: cucurucho de castañas del puesto de la castañera. Foto antes de que se enfríen.',
    cover: 'castanas',
  },
  {
    n: 15,
    title: 'Huesos de santo y buñuelos',
    category: 'tradiciones',
    difficulty: 'facil',
    points: 60,
    type: 'photo',
    starts: '2026-10-25 00:00+02',
    ends: '2026-11-03 23:59+01',
    description:
      'Todos los Santos se celebra comiendo. Foto de tus huesos de santo o buñuelos de viento.',
    cover: 'bunuelos',
  },
  {
    n: 24,
    title: 'El décimo de Navidad',
    category: 'tradiciones',
    difficulty: 'facil',
    points: 50,
    type: 'photo',
    starts: '2026-11-15 00:00+01',
    ends: '2026-12-22 14:00+01',
    description:
      'Empieza la temporada de lotería. Foto de tu décimo (¡tapa los números de serie!) y comparte el número que te da buena espina.',
    cover: 'loteria',
  },
  {
    n: 16,
    title: 'Mascota rojigualda',
    category: 'tradiciones',
    difficulty: 'facil',
    points: 60,
    type: 'photo',
    description:
      'Tu perro o tu gato con los colores de España: pañuelo, collar o lo que se deje poner (sin que sufra).',
    cover: 'mascota',
  },
  // --- Humor y solidaridad --------------------------------------------------------
  {
    n: 21,
    title: 'Frase de cuñado',
    category: 'humor',
    difficulty: 'facil',
    points: 40,
    type: 'manual',
    description:
      'Cuéntanos la frase más cuñada que hayas oído en la sobremesa ("esto en mi pueblo es gratis", "yo eso lo arreglo en un momento"…). Sin nombres: el cuñado es un concepto.',
    cover: 'cunado',
  },
  {
    n: 22,
    title: 'Siesta de pijama y orinal',
    category: 'humor',
    difficulty: 'facil',
    points: 40,
    type: 'manual',
    description:
      'Patrimonio inmaterial: cuéntanos tu siesta épica (duración, lugar y si hubo babas). La comunidad decide si es digna.',
    cover: 'siesta',
  },
  {
    n: 8,
    title: 'Una mañana por tu gente',
    category: 'solidaridad',
    difficulty: 'dificil',
    points: 200,
    type: 'manual',
    description:
      'Dedica una mañana a una ONG, banco de alimentos o parroquia de tu ciudad. Cuéntanos dónde fuiste y la comunidad lo validará.',
    cover: 'voluntariado',
  },
]
